name = "beneficiaries"
compatibility_date = "2024-01-15"

# Static assets configuration for Pages/Workers
[assets]
directory = "./dist"

[env.production]
name = "beneficiary-designation-api"

[env.staging]
name = "beneficiary-designation-api-staging"

# Optional: Custom domain configuration (uncomment and modify as needed)
# [[env.production.routes]]
# pattern = "yourapp.com"
# custom_domain = true

# Environment variables (set these via Cloudflare dashboard or wrangler secrets)
# [vars]
# NODE_ENV = "production"
